---
- include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: disable-other-firewalls.yml

- name: Install iptables
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ iptables_packages }}"

- name: Setting iptables_v4 rules
  template:
    src: iptables_v4.j2
    dest: "{{ iptables_rule_file.v4 }}"
  notify: restore iptables_v4
