---
- name: Converge
  hosts: all
  vars:
    iptables_v4_policy:
      input: ACCEPT
      output: ACCEPT
      forward: DROP
    iptables_v6_policy:
      input: ACCEPT
      output: ACCEPT
      forward: DROP
    iptables_security:
      accept_icmp_reply: true
      ignore_bogus_tcp: true
      prevent_port_scan: false
    iptables_allowed_client_ports:
      - { port: 22, protocol: tcp }
    iptables_allowed_server_ports:
      - { port: 22, protocol: tcp }

  pre_tasks:
    - name: Install Dependencies.
      yum: name=libselinux-python
      when: ansible_os_family == 'RedHat'
      changed_when: false

  roles:
    - role: ansible-role-iptables
